name: ci

on:
  push:
    branches: [main, master]
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt ruff
      - run: ruff check .

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt mypy types-requests types-urllib3
      - run: mypy webwork

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest -q

  security:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install --upgrade pip
      - run: pip install bandit pip-audit -r requirements.txt
      - name: Bandit
        run: |
          set -o pipefail
          bandit -q -r webwork | tee bandit.log
      - name: Pip audit
        run: |
          set -o pipefail
          pip-audit -r requirements.txt | tee pip-audit.log
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: security-logs
          path: |
            bandit.log
            pip-audit.log

  aggregate:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test, security]
    steps:
      - name: Status
        run: echo "All checks finished"
